from typing import Protocol

class NativeAdapter(Protocol):
    def load_instance(self): ...
    def reset_from_spec(self, reset: dict): ...
    def step_native_action(self, action): ...
    def get_policy_observation(self) -> dict: ...
    def render_capture(self, camera: dict, *, width: int, height: int) -> dict: ...
    def native_success(self) -> bool: ...
    def native_stage_state(self) -> dict: ...
    def get_named_body_state(self) -> dict: ...
    def export_reference_for_evaluator(self, out): ...
    def close(self): ...
