"""Tests for agents/eval/build_audit.py (Task 05).

Fixtures live under tests/data/builds/audit_fixture/<scenario>/ and are
minimal, hand-written JSON trees matching the real component schemas
documented at the top of agents/eval/build_audit.py (report.json,
render_metrics_v2.json, drop_v2.json, inpaint/obj_XX/plane.json,
inpaint/verify/verify_report.json, objects/obj_XX/{aligned,hybrid}.json,
eval_vs_gt.json). Regenerated by scratchpad's gen_fixtures.py if ever needed.

Run: .venv/bin/python -m pytest -q tests/test_build_audit.py
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "data" / "builds" / "audit_fixture"

sys.path.insert(0, str(ROOT))
from agents.eval import build_audit as ba  # noqa: E402


def audit(name: str) -> dict:
    return ba.run_audit(FIXTURES / name)


# --------------------------------------------------------------------------
# The one invariant that matters: status is always one of the 4 values, and
# missing evidence is always not_applicable, never pass.
# --------------------------------------------------------------------------

ALL_FIXTURES = ["happy_path", "ghost_object", "penetration", "missing_support",
                "bad_scale", "transparent_residue", "mixed_scene", "no_evidence"]


@pytest.mark.parametrize("name", ALL_FIXTURES)
def test_every_status_is_one_of_the_four_values(name):
    a = audit(name)
    for check_name, res in a["checks"].items():
        assert res["status"] in ba.VALID_STATUSES, (check_name, res)
    for obj in a["objects"]:
        assert obj["object_status"] in ba.VALID_STATUSES
        for check_name, res in obj["checks"].items():
            assert res["status"] in ba.VALID_STATUSES, (obj["object_id"], check_name, res)
    assert a["overall_status"] in ba.VALID_STATUSES


def test_missing_evidence_is_not_applicable_never_pass():
    """The build has zero discovered objects and no other artifact at all.
    Every check must degrade to not_applicable; none may silently read as
    pass just because there was nothing to disagree with."""
    a = audit("no_evidence")
    assert a["overall_status"] == ba.STATUS_NA
    for check_name, res in a["checks"].items():
        assert res["status"] == ba.STATUS_NA, f"{check_name} was {res['status']}, expected not_applicable"
        assert res["status"] != ba.STATUS_PASS
    assert a["objects"] == []
    assert a["repair_queue"] == []


def test_specific_missing_evidence_example_verify_report_json():
    """Literal example from the task spec: no verify_report.json (and no
    verify_render.json either, in this fixture) present -> the removal
    checks must be not_applicable, never pass, even though the build is
    otherwise healthy (ghost_object fixture has no inpaint/ dir at all)."""
    a = audit("ghost_object")
    for check_name in ("removal_alpha_coverage", "removal_depth_residual",
                       "removal_redetection"):
        res = a["checks"][check_name]
        assert res["status"] == ba.STATUS_NA
        assert res["status"] != ba.STATUS_PASS


# --------------------------------------------------------------------------
# The 5 mandatory synthetic fixtures: each must trip its OWN distinct check,
# and leave unrelated checks alone (no generic "something's wrong" blob).
# --------------------------------------------------------------------------

def test_ghost_object_fixture_triggers_only_ghost_object():
    a = audit("ghost_object")
    assert a["checks"]["ghost_object"]["status"] == ba.STATUS_FAIL
    assert "never entered physics" in a["checks"]["ghost_object"]["reason"]
    # unrelated checks on the SAME object must stay clean, not cascade
    obj = a["objects"][0]
    assert obj["checks"]["registration_residual"]["status"] == ba.STATUS_PASS
    assert obj["checks"]["scale_sanity"]["status"] == ba.STATUS_PASS
    assert obj["object_status"] == ba.STATUS_FAIL  # ghost_object alone drives it
    assert any(item["stage"] == "ghost_object" for item in a["repair_queue"])


def test_penetration_fixture_triggers_penetration():
    a = audit("penetration")
    assert a["checks"]["penetration"]["status"] == ba.STATUS_FAIL
    assert a["checks"]["penetration"]["reason"].count("sank") or \
        "sank" in a["checks"]["penetration"]["reason"]
    # settle_drift is a genuinely different signal (drift magnitude) and must
    # NOT be dragged down just because the object also sank
    assert a["checks"]["settle_drift"]["status"] == ba.STATUS_PASS
    assert a["checks"]["scale_sanity"]["status"] == ba.STATUS_PASS
    assert a["checks"]["registration_residual"]["status"] == ba.STATUS_PASS
    assert any(item["stage"] == "penetration" for item in a["repair_queue"])


def test_missing_support_fixture_triggers_support_overlap():
    a = audit("missing_support")
    assert a["checks"]["support_overlap"]["status"] == ba.STATUS_FAIL
    assert "support" in a["checks"]["support_overlap"]["reason"]
    # this must be distinct from penetration/drop_response/settle_drift
    for other in ("penetration", "drop_response", "settle_drift", "ghost_object",
                  "scale_sanity", "registration_residual"):
        assert a["checks"][other]["status"] == ba.STATUS_PASS, other
    assert any(item["stage"] == "support_overlap" for item in a["repair_queue"])


def test_bad_scale_fixture_triggers_only_scale_sanity():
    a = audit("bad_scale")
    assert a["checks"]["scale_sanity"]["status"] == ba.STATUS_FAIL
    assert "outside the accepted" in a["checks"]["scale_sanity"]["reason"]
    # a good chamfer residual must not be swept up into the scale failure
    assert a["checks"]["registration_residual"]["status"] == ba.STATUS_PASS
    assert a["checks"]["ghost_object"]["status"] == ba.STATUS_PASS
    assert a["checks"]["penetration"]["status"] == ba.STATUS_PASS
    entry = [i for i in a["repair_queue"] if i["stage"] == "scale_sanity"]
    assert entry and entry[0]["object_id"] == "obj_00"


def test_transparent_residue_fixture_triggers_all_three_removal_checks():
    a = audit("transparent_residue")
    for check_name in ("removal_alpha_coverage", "removal_depth_residual",
                       "removal_redetection"):
        assert a["checks"][check_name]["status"] == ba.STATUS_FAIL, check_name
    # each is independently identifiable, not a single collapsed flag
    assert "alpha coverage" in a["checks"]["removal_alpha_coverage"]["reason"]
    assert "depth-vs-plane" in a["checks"]["removal_depth_residual"]["reason"]
    assert "detection score" in a["checks"]["removal_redetection"]["reason"]
    # physics/registration for the same object is unaffected
    assert a["checks"]["registration_residual"]["status"] == ba.STATUS_PASS
    assert a["checks"]["drop_response"]["status"] == ba.STATUS_PASS
    stages = {i["stage"] for i in a["repair_queue"]}
    assert {"removal_alpha_coverage", "removal_depth_residual",
            "removal_redetection"} <= stages


# --------------------------------------------------------------------------
# A failing check cannot be averaged away by unrelated passing objects.
# --------------------------------------------------------------------------

def test_failed_check_not_averaged_away_by_passing_objects():
    a = audit("mixed_scene")
    pen = a["checks"]["penetration"]
    assert pen["status"] == ba.STATUS_FAIL
    assert pen["counts"]["pass"] == 3
    assert pen["counts"]["fail"] == 1
    assert pen["worst_object"] == "obj_03"
    # the scene-level JSON must never carry an averaged numeric score that
    # could be misread as "mostly fine" -- confirm no such field exists
    assert "score" not in pen and "mean" not in pen
    # and the failure must propagate to the overall verdict regardless of
    # the 3 passing objects sitting right next to it
    assert a["overall_status"] == ba.STATUS_FAIL

    per_object_statuses = [o["object_status"] for o in a["objects"]]
    assert per_object_statuses.count(ba.STATUS_PASS) == 3
    assert per_object_statuses.count(ba.STATUS_FAIL) == 1


# --------------------------------------------------------------------------
# Determinism across reruns.
# --------------------------------------------------------------------------

def test_audit_is_deterministic_across_reruns():
    a1 = audit("mixed_scene")
    a2 = audit("mixed_scene")
    assert a1 == a2

    a1 = audit("happy_path")
    a2 = audit("happy_path")
    assert a1 == a2


def test_audit_is_deterministic_byte_for_byte_json():
    build_dir = FIXTURES / "mixed_scene"
    a1 = ba.run_audit(build_dir)
    a2 = ba.run_audit(build_dir)
    assert json.dumps(a1, indent=1) == json.dumps(a2, indent=1)


# --------------------------------------------------------------------------
# Happy path: a clean build should read as pass, with the two
# pending-upstream categories explicitly not_applicable, not silently
# skipped or promoted.
# --------------------------------------------------------------------------

def test_happy_path_is_pass_overall():
    a = audit("happy_path")
    assert a["overall_status"] == ba.STATUS_PASS
    for check_name in ("ghost_object", "registration_residual", "scale_sanity",
                       "removal_alpha_coverage", "removal_depth_residual",
                       "removal_redetection", "penetration", "support_overlap",
                       "settle_drift", "drop_response", "reconstruction_coverage",
                       "held_out_rendering", "duplicate_instances",
                       "missing_instances", "candidate_disagreement"):
        assert a["checks"][check_name]["status"] == ba.STATUS_PASS, check_name


def test_room_collision_and_alignment_checks_are_not_applicable_pending_upstream():
    """Task 06 (room_collision.py) and Task 04 (robot_align.py /
    alignment_report.py) have not landed yet -- every fixture must expose
    these four + two checks as not_applicable with a reason naming the
    pending task, never fail (no evidence to fail on) and never pass."""
    for name in ALL_FIXTURES:
        a = audit(name)
        for check_name in ("room_collision_coverage", "room_disconnected_components",
                           "room_penetration_max", "room_settle_drift"):
            res = a["checks"][check_name]
            assert res["status"] == ba.STATUS_NA
            assert "Task 06" in res["reason"]
        for check_name in ("metric_scale", "robot_alignment"):
            res = a["checks"][check_name]
            assert res["status"] == ba.STATUS_NA
            assert "Task 04" in res["reason"]


# --------------------------------------------------------------------------
# Schema shape / bookkeeping.
# --------------------------------------------------------------------------

def test_schema_version_present():
    a = audit("happy_path")
    assert a["schema_version"] == ba.SCHEMA_VERSION
    assert isinstance(a["schema_version"], str)


def test_object_summaries_link_to_evidence_paths_not_inline_blobs():
    a = audit("happy_path")
    obj = a["objects"][0]
    assert obj["evidence"]["aligned_json"] == "objects/obj_00/aligned.json"
    assert (FIXTURES / "happy_path" / obj["evidence"]["aligned_json"]).exists()
    # per-object checks must be compact (status/reason/small numeric fields),
    # never the full upstream JSON blob inlined
    for res in obj["checks"].values():
        assert "views" not in res and "detail" not in res


def test_repair_queue_shape():
    a = audit("bad_scale")
    for item in a["repair_queue"]:
        assert set(item) == {"object_id", "stage", "reason"}


def test_thresholds_reused_from_existing_pipeline_are_not_redefined_arbitrarily():
    # these must match the frozen upstream constants verbatim -- see the
    # inline citations in agents/eval/build_audit.py
    assert ba.DROP_STABLE_DRIFT_M == 0.03
    assert ba.DROP_SUNK_Z_M == -0.05
    assert ba.SIZE_RATIO_RANGE == (0.4, 2.5)
    assert ba.REDETECTION_FAIL_SCORE == 0.5


# --------------------------------------------------------------------------
# CLI smoke test.
# --------------------------------------------------------------------------

def test_cli_writes_audit_json_and_human_report(tmp_path):
    build_dir = tmp_path / "happy_path"
    shutil.copytree(FIXTURES / "happy_path", build_dir)
    proc = subprocess.run(
        [sys.executable, "-m", "agents.eval.build_audit", str(build_dir)],
        cwd=ROOT, capture_output=True, text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
    out_json = build_dir / "build_audit.json"
    out_md = build_dir / "build_audit_report.md"
    assert out_json.exists() and out_md.exists()
    written = json.loads(out_json.read_text())
    assert written["overall_status"] == ba.STATUS_PASS
    assert "Overall: PASS" in out_md.read_text()


def test_cli_nonzero_exit_on_fail(tmp_path):
    build_dir = tmp_path / "bad_scale"
    shutil.copytree(FIXTURES / "bad_scale", build_dir)
    proc = subprocess.run(
        [sys.executable, "-m", "agents.eval.build_audit", str(build_dir)],
        cwd=ROOT, capture_output=True, text=True,
    )
    assert proc.returncode == 1, proc.stdout + proc.stderr


# --------------------------------------------------------------------------
# Mutation sanity: flipping evidence flips exactly the check it should.
# --------------------------------------------------------------------------

def test_flipping_trim_ok_flips_only_support_overlap(tmp_path):
    build_dir = tmp_path / "b"
    shutil.copytree(FIXTURES / "happy_path", build_dir)
    a_before = ba.run_audit(build_dir)
    assert a_before["checks"]["support_overlap"]["status"] == ba.STATUS_PASS

    plane_path = build_dir / "inpaint" / "obj_00" / "plane.json"
    plane = json.loads(plane_path.read_text())
    plane["trim_ok"] = False
    plane_path.write_text(json.dumps(plane))

    a_after = ba.run_audit(build_dir)
    assert a_after["checks"]["support_overlap"]["status"] == ba.STATUS_FAIL
    # nothing else should have moved
    for check_name in a_before["checks"]:
        if check_name == "support_overlap":
            continue
        assert a_before["checks"][check_name]["status"] == a_after["checks"][check_name]["status"], check_name
