"""Factory V_mesh HYBRID slot: per object, keep the better of the existing
TRELLIS asset (single best-view image-to-3D, s4_trellis) and a ReconViaGen
asset (multi-view VGGT-conditioned TRELLIS, s4_reconviagen) -- selected by
the SYMMETRIC CLIPPED CHAMFER residual (s5_align.sym_score) after both have
been registered with the same factory_align machinery.

Motivation (RVG pilot on c50d2d1d42): RVG mean F1@20mm 0.713 vs TRELLIS
0.635, but RVG collapses on a transparent bottle (0.014) where TRELLIS is
fine (0.817) -- the registration residual arbitrates per object.

Per non-rejected object in $SIMANY_OUT/objects/objects.json:
  1. snapshot the pre-hybrid canonical files into obj_XX/trellis/ (once;
     the snapshot is the authoritative TRELLIS candidate on reruns);
  2. generate the RVG asset into obj_XX/rvg/ (rvg_mesh.ply + rvg_gs.ply,
     cached if both already exist) -- the TRELLIS asset is NEVER regenerated;
  3. register the RVG mesh exactly like factory_align (same align_object,
     same tiers/size gate) -> obj_XX/rvg/aligned.json;
  4. score both registered candidates with sym_score against gt_points.ply
     and pick the winner (an RVG asset that is tier-C/rejected or lacks
     gaussians can never win);
  5. write obj_XX/hybrid.json and materialize the winner into the canonical
     files downstream reads (trellis_gs.ply, trellis_mesh.ply, mesh_sim.*,
     aligned.json, collision/, object.urdf) via atomic copies; collision +
     URDF are rebuilt with the s6 machinery (physics params reused from
     physics.json, no VLM call).

Additive only: non-hybrid pipeline files are untouched, originals live on
under obj_XX/trellis/ and obj_XX/rvg/. Reruns are idempotent (a TRELLIS win
restores the snapshot). GPU, venv (torch 2.4.1).

SIMANY_HYBRID_CANDIDATES (default "trellis,rvg" = historical behavior) picks
the candidate set; adding "sam3d" enters obj_XX/sam3d/ assets (sam3d_mesh.ply
+ sam3d_gs.ply, pre-generated by `run_sam3d agents.models.s4_sam3d` under its own
.envs/sam3d-objects env -- this venv can only consume, never generate them)
into the same registration + sym_score contest.
Usage: factory_hybrid.py [--objects 0,3,...] [--n-views 12]
"""
import argparse
import json
import os
import shutil
import time
import traceback

import numpy as np

from agents.core import common as C
# s4_reconviagen module import also installs the xformers BlockDiagonalMask
# monkey-patch, the rembg stub, and puts the ReconViaGen repo root + its
# wheels/vggt dir on sys.path (so `trellis` resolves to the RVG fork here).
from agents.models.s4_reconviagen import collect_views
from agents.assets.factory_align import (ALIGN_TGT_SAMPLES, SIZE_RATIO_RANGE, TIER_A_F1_20,
                           TIER_B_F1_40)
from agents.assets.s5_align import align_object, apply_T, f1_eval, sym_score
from agents.assets.s6_physics import coacd_parts, write_urdf

# NOTE: do NOT import s4_trellis here -- its module-level sys.path.insert of
# the original TRELLIS repo would shadow the RVG fork's `trellis` package.
# (agents.models.s4_sam3d is likewise NEVER imported: it only runs under the
# dedicated .envs/sam3d-objects interpreter.)
CANDIDATES = [c.strip() for c in os.environ.get(
    "SIMANY_HYBRID_CANDIDATES", "trellis,rvg").split(",") if c.strip()]
SIM_TRIS = 40_000  # same decimation budget as s4_trellis.SIM_TRIS
N_MESH_SAMPLES = 20_000
# canonical per-object files that hybrid selection may replace
CANON_FILES = ["trellis_mesh.ply", "trellis_gs.ply", "mesh_sim.ply",
               "mesh_sim.obj", "aligned.json", "object.urdf", "physics.json"]


def copy_atomic(src, dst):
    tmp = dst.parent / (dst.stem + ".hybtmp" + dst.suffix)
    shutil.copyfile(src, tmp)
    os.replace(tmp, dst)


def snapshot_trellis(odir):
    """One-time snapshot of the pre-hybrid canonicals -> obj_XX/trellis/.
    Guarded by a marker so a rerun never re-snapshots mutated canonicals."""
    tdir = odir / "trellis"
    if (tdir / ".snapshot_done").exists():
        return tdir
    tdir.mkdir(exist_ok=True)
    for f in CANON_FILES:
        if (odir / f).exists():
            copy_atomic(odir / f, tdir / f)
    cdir = odir / "collision"
    if cdir.is_dir():
        (tdir / "collision").mkdir(exist_ok=True)
        for p in sorted(cdir.glob("part_*.obj")):
            copy_atomic(p, tdir / "collision" / p.name)
    (tdir / ".snapshot_done").touch()
    return tdir


def make_align_record(meta, mesh, mesh_pts, tgt):
    """factory_align's per-object registration + tiering, verbatim schema."""
    tgt_align = tgt[:: max(len(tgt) // ALIGN_TGT_SAMPLES, 1)]
    T, chamfer, chamfer_init, tilt = align_object(mesh_pts, tgt_align)
    s, _, _ = C.decompose_similarity(T)
    ev = f1_eval(apply_T(T, mesh_pts), tgt)
    world_dims = s * (mesh.vertices.max(axis=0) - mesh.vertices.min(axis=0))
    ratio = float(np.max(world_dims)) / max(float(np.max(meta["extent"])), 1e-6)
    rec = {"index": meta["index"], "label": meta["label"], "scale": s,
           "T": T, "chamfer_med_m": chamfer, "chamfer_init_m": chamfer_init,
           "icp_tilt_deg": tilt, "eval": ev, "world_dims": world_dims,
           "size_ratio_vs_obs": ratio}
    f20 = ev["f1@20mm"]["f1"]
    f40 = ev["f1@40mm"]["f1"]
    if not (SIZE_RATIO_RANGE[0] <= ratio <= SIZE_RATIO_RANGE[1]):
        rec["tier"] = "C"
        rec["rejected"] = f"size ratio {ratio:.2f} outside {SIZE_RATIO_RANGE}"
    elif f20 >= TIER_A_F1_20:
        rec["tier"] = "A"
    elif f40 >= TIER_B_F1_40:
        rec["tier"] = "B"
    else:
        rec["tier"] = "C"
        rec["rejected"] = f"F1@20mm {f20:.2f} / @40mm {f40:.2f} below tier B"
    return rec


def sample_mesh(path):
    import trimesh
    mesh = trimesh.load(path, process=False)
    pts, _ = trimesh.sample.sample_surface(mesh, N_MESH_SAMPLES)
    return mesh, np.asarray(pts, dtype=np.float64)


def registered_residual(mesh_path, T, tgt, tgt_tree):
    _, pts = sample_mesh(mesh_path)
    return float(sym_score(apply_T(np.asarray(T, np.float64), pts),
                           tgt, tgt_tree))


def build_sim_mesh(odir, src_mesh_ply):
    """s4_trellis's decimation for the canonical mesh_sim.ply/.obj."""
    import open3d as o3d
    import trimesh
    om = o3d.io.read_triangle_mesh(str(src_mesh_ply))
    if len(om.triangles) > SIM_TRIS:
        om = om.simplify_quadric_decimation(SIM_TRIS)
    om.remove_degenerate_triangles()
    tmp_ply = odir / "mesh_sim.hybtmp.ply"
    o3d.io.write_triangle_mesh(str(tmp_ply), om)
    os.replace(tmp_ply, odir / "mesh_sim.ply")
    tmp_obj = odir / "mesh_sim.hybtmp.obj"
    trimesh.Trimesh(np.asarray(om.vertices), np.asarray(om.triangles),
                    process=False).export(tmp_obj, file_type="obj")
    os.replace(tmp_obj, odir / "mesh_sim.obj")


def load_physics(odir, label):
    pj = odir / "trellis" / "physics.json"
    if not pj.exists():
        pj = odir / "physics.json"
    if pj.exists():
        return json.loads(pj.read_text())
    mass, fric = C.FALLBACK_PHYSICS.get(label, (0.3, 0.5))
    return {"mass_kg": mass, "friction": fric, "restitution": 0.1,
            "source": "fallback"}


def materialize_rvg(odir, meta, rec):
    """Make the RVG asset the canonical one (snapshot already taken)."""
    import trimesh
    rdir = odir / "rvg"
    copy_atomic(rdir / "rvg_mesh.ply", odir / "trellis_mesh.ply")
    copy_atomic(rdir / "rvg_gs.ply", odir / "trellis_gs.ply")
    build_sim_mesh(odir, rdir / "rvg_mesh.ply")
    rec = dict(rec)
    rec["vmesh_source"] = "rvg"
    C.save_json(odir / "aligned.json", rec)
    # collision + URDF via the s6 machinery, physics params reused
    tm = trimesh.load(odir / "mesh_sim.ply", process=False)
    ext_canon = tm.vertices.max(axis=0) - tm.vertices.min(axis=0)
    s = rec["scale"]
    files = coacd_parts(odir, world_max_dim=float((ext_canon * s).max()))
    phys = load_physics(odir, meta["label"])
    write_urdf(odir, f"obj_{meta['index']:02d}", s,
               np.maximum(ext_canon * s, 1e-3), phys, files,
               tm.vertices.mean(axis=0) * s)
    C.save_json(odir / "physics.json", phys)
    print(f"[hy] obj_{meta['index']:02d}: canonical <- RVG "
          f"({len(files)} convex parts)")


def materialize_sam3d(odir, meta, rec):
    """Make the SAM3D asset the canonical one (same recipe as materialize_rvg)."""
    import trimesh
    sdir = odir / "sam3d"
    copy_atomic(sdir / "sam3d_mesh.ply", odir / "trellis_mesh.ply")
    copy_atomic(sdir / "sam3d_gs.ply", odir / "trellis_gs.ply")
    build_sim_mesh(odir, sdir / "sam3d_mesh.ply")
    rec = dict(rec)
    rec["vmesh_source"] = "sam3d"
    C.save_json(odir / "aligned.json", rec)
    tm = trimesh.load(odir / "mesh_sim.ply", process=False)
    ext_canon = tm.vertices.max(axis=0) - tm.vertices.min(axis=0)
    s = rec["scale"]
    files = coacd_parts(odir, world_max_dim=float((ext_canon * s).max()))
    phys = load_physics(odir, meta["label"])
    write_urdf(odir, f"obj_{meta['index']:02d}", s,
               np.maximum(ext_canon * s, 1e-3), phys, files,
               tm.vertices.mean(axis=0) * s)
    C.save_json(odir / "physics.json", phys)
    print(f"[hy] obj_{meta['index']:02d}: canonical <- SAM3D "
          f"({len(files)} convex parts)")


def materialize_trellis(odir, meta):
    """Restore the snapshot as canonical (no-op content-wise on 1st run)."""
    tdir = odir / "trellis"
    for f in CANON_FILES:
        if (tdir / f).exists():
            copy_atomic(tdir / f, odir / f)
    (odir / "collision").mkdir(exist_ok=True)
    for p in sorted((tdir / "collision").glob("part_*.obj")):
        copy_atomic(p, odir / "collision" / p.name)
    rec = json.loads((odir / "aligned.json").read_text())
    rec["vmesh_source"] = "trellis"
    C.save_json(odir / "aligned.json", rec)


def gaussian_frame_check(rdir):
    """Log-only sanity: RVG gaussians must share the mesh's canonical frame."""
    from plyfile import PlyData
    import trimesh
    g = PlyData.read(str(rdir / "rvg_gs.ply"))["vertex"]
    gxyz = np.stack([np.asarray(g[a]) for a in "xyz"], axis=1)
    mv = trimesh.load(rdir / "rvg_mesh.ply", process=False).vertices
    print(f"[hy]   frame check: gs aabb {gxyz.min(0).round(3)}"
          f"..{gxyz.max(0).round(3)} vs mesh {mv.min(0).round(3)}"
          f"..{mv.max(0).round(3)}")


def run_rvg(pipe_holder, meta, odir, gt, ctx, n_views, *, precollected_views=None):
    """Generate rvg/rvg_mesh.ply + rvg_gs.ply (cached if both exist)."""
    import torch
    import trimesh
    from PIL import Image

    rdir = odir / "rvg"
    rdir.mkdir(exist_ok=True)
    if (rdir / "rvg_mesh.ply").exists() and (rdir / "rvg_gs.ply").exists():
        print(f"[hy] obj_{meta['index']:02d}: rvg asset cached, skip gen")
        return 0.0

    if pipe_holder["pipe"] is None:
        if os.environ.get("SIMANY_RVG_PINNED_CONFIG"):
            from agents.models.rvg_pinned import load_pipeline
            pipe = load_pipeline(os.environ["SIMANY_RVG_PINNED_CONFIG"])
        else:
            from trellis.pipelines import TrellisVGGTTo3DPipeline
            pipe = TrellisVGGTTo3DPipeline.from_pretrained(
                "Stable-X/trellis-vggt-v0-2")
        # their low_vram path forgets to move the slat conditioning modules;
        # the A6000 fits the whole no-refinement pipeline (same as pilot)
        pipe.low_vram = False
        if hasattr(pipe, "cuda"):
            pipe.cuda()
        for mod in pipe.models.values():
            mod.to("cuda")
        for attr in vars(pipe).values():
            if isinstance(attr, torch.nn.Module):
                attr.to("cuda")
        pipe_holder["pipe"] = pipe
    pipe = pipe_holder["pipe"]

    K, W, H, w2c_all, scene_full, verts, faces = ctx
    t0 = time.time()
    views = precollected_views if precollected_views is not None else collect_views(
        gt, K, W, H, w2c_all, scene_full, verts, faces, n_views)
    if len(views) < 2:
        raise RuntimeError(f"only {len(views)} usable views")
    imgs = []
    for k, (fname, (u0, v0, u1, v1), mask) in enumerate(views):
        rgb = np.asarray(Image.open(C.IMAGES_DIR / fname).convert("RGB"))
        rgba = np.dstack([rgb[v0:v1, u0:u1], (mask * 255).astype(np.uint8)])
        pil = Image.fromarray(rgba)
        pil.save(rdir / f"view_{k:02d}.png")
        imgs.append(pipe.preprocess_image(pil))
    print(f"[hy] obj_{meta['index']:02d} {meta['label']}: {len(imgs)} views")

    out, _, _ = pipe.run(image=imgs, seed=42, formats=["mesh", "gaussian"],
                         preprocess_image=False)
    mesh = out["mesh"][0]
    v = mesh.vertices.cpu().numpy().astype(np.float64)
    f = mesh.faces.cpu().numpy()
    cols = None
    if getattr(mesh, "vertex_attrs", None) is not None \
            and mesh.vertex_attrs.shape[-1] >= 3:
        cols = (mesh.vertex_attrs[:, :3].clamp(0, 1).cpu().numpy()
                * 255).astype(np.uint8)
    trimesh.Trimesh(v, f, vertex_colors=cols, process=False).export(
        rdir / "rvg_mesh.ply")
    # RVG's Gaussian.save_ply(path) takes no transform kwarg and writes the
    # raw canonical coords -- already the same frame as the mesh above
    out["gaussian"][0].save_ply(str(rdir / "rvg_gs.ply"))
    n_gs = out["gaussian"][0].get_xyz.shape[0]
    del out
    torch.cuda.empty_cache()
    dt = time.time() - t0
    print(f"[hy] obj_{meta['index']:02d}: rvg mesh {len(v)}v/{len(f)}f, "
          f"gs {n_gs}, {dt:.0f}s")
    gaussian_frame_check(rdir)
    return dt


def main():
    import open3d as o3d
    from scipy.spatial import cKDTree
    from agents.assets.s5_align import scene_mesh_arrays

    ap = argparse.ArgumentParser()
    ap.add_argument("--objects", default=None,
                    help="comma-separated indices (default: all non-rejected)")
    ap.add_argument("--n-views", type=int, default=12)
    args = ap.parse_args()

    t_start = time.time()
    K, W, H, _ = C.load_intrinsics()
    w2c_all = sorted(C.load_colmap_w2c().items())
    verts, faces = scene_mesh_arrays()
    scene_full = C.make_raycast_scene()
    gts = {g["object_id"]: g for g in C.load_instances()}
    ctx = (K, W, H, w2c_all, scene_full, verts, faces)

    objects = json.loads((C.OUT / "objects" / "objects.json").read_text())
    picks = None if args.objects is None \
        else {int(x) for x in args.objects.split(",")}
    pipe_holder = {"pipe": None}
    rows = []

    for meta in objects:
        idx = meta["index"]
        if picks is not None and idx not in picks:
            continue
        odir = C.OUT / "objects" / f"obj_{idx:02d}"
        if not (odir / "aligned.json").exists() \
                or not (odir / "trellis_mesh.ply").exists():
            print(f"[hy] obj_{idx:02d} {meta['label']}: no TRELLIS asset, skip")
            continue
        tdir = snapshot_trellis(odir)
        trec = json.loads((tdir / "aligned.json").read_text())
        if trec.get("rejected"):
            print(f"[hy] obj_{idx:02d} {meta['label']}: rejected "
                  f"({trec['rejected']}), skip")
            continue

        tgt = np.asarray(o3d.io.read_point_cloud(
            str(odir / "gt_points.ply")).points)
        tgt_tree = cKDTree(tgt)
        res_t = registered_residual(tdir / "trellis_mesh.ply", trec["T"],
                                    tgt, tgt_tree)

        row = {"index": idx, "label": meta["label"],
               "criterion": "sym_score (symmetric clipped chamfer, "
                            "clip=0.03m) vs gt_points.ply",
               "sym_chamfer_trellis_m": res_t,
               "trellis": {"chamfer_med_m": trec["chamfer_med_m"],
                           "f1_20": trec["eval"]["f1@20mm"]["f1"],
                           "f1_40": trec["eval"]["f1@40mm"]["f1"],
                           "tier": trec["tier"], "scale": trec["scale"]},
               "sym_chamfer_rvg_m": None, "rvg": None, "rvg_error": None}

        gt = gts.get(meta.get("gt_object_id"))
        rrec = None
        if "rvg" in CANDIDATES:
            try:
                if gt is None:
                    raise RuntimeError("no instance for view collection")
                row["gen_seconds"] = run_rvg(pipe_holder, meta, odir, gt, ctx,
                                             args.n_views)
                mesh_r, pts_r = sample_mesh(odir / "rvg" / "rvg_mesh.ply")
                rrec = make_align_record(meta, mesh_r, pts_r, tgt)
                C.save_json(odir / "rvg" / "aligned.json", rrec)
                res_r = float(sym_score(apply_T(np.asarray(rrec["T"]), pts_r),
                                        tgt, tgt_tree))
                row["sym_chamfer_rvg_m"] = res_r
                row["rvg"] = {"chamfer_med_m": rrec["chamfer_med_m"],
                              "f1_20": rrec["eval"]["f1@20mm"]["f1"],
                              "f1_40": rrec["eval"]["f1@40mm"]["f1"],
                              "tier": rrec["tier"], "scale": rrec["scale"],
                              "rejected": rrec.get("rejected")}
            except Exception as e:
                traceback.print_exc()
                row["rvg_error"] = f"{type(e).__name__}: {e}"

        srec = None
        if "sam3d" in CANDIDATES:
            row.update({"sym_chamfer_sam3d_m": None, "sam3d": None,
                        "sam3d_error": None})
            try:
                sdir = odir / "sam3d"
                if not ((sdir / "sam3d_mesh.ply").exists()
                        and (sdir / "sam3d_gs.ply").exists()):
                    raise RuntimeError(
                        "sam3d asset missing; generate it first with "
                        "`run_sam3d agents.models.s4_sam3d` (.envs/sam3d-objects)")
                mesh_s, pts_s = sample_mesh(sdir / "sam3d_mesh.ply")
                srec = make_align_record(meta, mesh_s, pts_s, tgt)
                C.save_json(sdir / "aligned.json", srec)
                res_s = float(sym_score(apply_T(np.asarray(srec["T"]), pts_s),
                                        tgt, tgt_tree))
                row["sym_chamfer_sam3d_m"] = res_s
                row["sam3d"] = {"chamfer_med_m": srec["chamfer_med_m"],
                                "f1_20": srec["eval"]["f1@20mm"]["f1"],
                                "f1_40": srec["eval"]["f1@40mm"]["f1"],
                                "tier": srec["tier"], "scale": srec["scale"],
                                "rejected": srec.get("rejected")}
            except Exception as e:
                traceback.print_exc()
                row["sam3d_error"] = f"{type(e).__name__}: {e}"

        # winner: lowest sym_score; ties keep the earlier entry, so TRELLIS
        # stays the fallback exactly as in the two-way version
        best, best_res = "trellis", row["sym_chamfer_trellis_m"]
        for name, rec in (("rvg", rrec), ("sam3d", srec)):
            if row.get(name) is not None and not rec.get("rejected") \
                    and row[f"sym_chamfer_{name}_m"] < best_res:
                best, best_res = name, row[f"sym_chamfer_{name}_m"]
        row["winner"] = best
        row["canonical_source"] = row["winner"]

        if row["winner"] == "rvg":
            materialize_rvg(odir, meta, rrec)
        elif row["winner"] == "sam3d":
            materialize_sam3d(odir, meta, srec)
        else:
            materialize_trellis(odir, meta)
        C.save_json(odir / "hybrid.json", row)
        rv = row["rvg"] or {}
        sam_ms = (f"/{(row.get('sym_chamfer_sam3d_m') or float('nan')) * 1000:.1f}mm"
                  if "sam3d" in CANDIDATES else "")
        print(f"[hy] obj_{idx:02d} {meta['label']}: WINNER {row['winner']}  "
              f"sym {res_t * 1000:.1f}mm vs "
              f"{(row['sym_chamfer_rvg_m'] or float('nan')) * 1000:.1f}mm"
              f"{sam_ms}  "
              f"F1@20 {row['trellis']['f1_20']:.3f} vs "
              f"{rv.get('f1_20', float('nan')):.3f}")
        rows.append(row)

    # refresh objects/aligned_all.json so report tooling sees the winners
    all_path = C.OUT / "objects" / "aligned_all.json"
    backup = C.OUT / "objects" / "aligned_all_prehybrid.json"
    if all_path.exists() and not backup.exists():
        copy_atomic(all_path, backup)
    recs = []
    for meta in objects:
        aj = C.OUT / "objects" / f"obj_{meta['index']:02d}" / "aligned.json"
        if aj.exists():
            recs.append(json.loads(aj.read_text()))
    C.save_json(all_path, recs)

    mean = lambda vals: float(np.mean(vals)) if vals else float("nan")
    f1_before = mean([r["trellis"]["f1_20"] for r in rows])
    f1_after = mean([(r.get(r["winner"]) or r["trellis"])["f1_20"]
                     for r in rows])
    n_rvg = sum(r["winner"] == "rvg" for r in rows)
    n_sam3d = sum(r["winner"] == "sam3d" for r in rows)
    summary = {"n_objects": len(rows), "candidates": CANDIDATES,
               "n_rvg_wins": n_rvg, "n_sam3d_wins": n_sam3d,
               "n_rvg_failed": sum(r["rvg_error"] is not None for r in rows),
               "n_sam3d_failed": sum(r.get("sam3d_error") is not None
                                     for r in rows),
               "mean_f1_20_trellis": f1_before,
               "mean_f1_20_hybrid": f1_after,
               "wall_seconds": time.time() - t_start, "rows": rows}
    C.save_json(C.OUT / "objects" / "hybrid_all.json", summary)
    print(f"[hy] DONE: {len(rows)} objects, RVG wins {n_rvg}, "
          f"SAM3D wins {n_sam3d}, "
          f"mean F1@20 {f1_before:.3f} -> {f1_after:.3f}, "
          f"{summary['wall_seconds'] / 60:.1f} min")


if __name__ == "__main__":
    main()
