"""Native LIBERO XML/state -> posed high-resolution RGB-D scene contract.

This is a simulator-sourced, GT-pose/GT-mesh input, not a real capture or
GT-free reconstruction. No screenshots are upscaled or generated by an image model.
"""
import argparse,json,math
from pathlib import Path
import xml.etree.ElementTree as ET
import numpy as np
from physicalview.phiview import save_json


def object_label(name):
    for words,label in [(['mug'],'mug'),(['bowl'],'bowl'),(['plate'],'plate'),(['bottle'],'bottle'),(['pot'],'kettle'),(['pan'],'tray'),(['basket'],'basket'),(['book'],'book'),(['soup','sauce'],'can')]:
        if any(w in name for w in words):return label
    return 'box'


def source_model(row):
    import mujoco
    from scipy.spatial.transform import Rotation
    tree=ET.parse(row['native_xml']);m=mujoco.MjModel.from_xml_string(ET.tostring(tree.getroot()).decode());d=mujoco.MjData(m)
    state=np.load(row['state_npz'])['state']
    if len(state)!=1+m.nq+m.nv:raise ValueError('Unsupported native state layout')
    d.qpos[:]=state[1:1+m.nq];d.qvel[:]=state[1+m.nq:];mujoco.mj_forward(m,d)
    names=[m.body(int(m.jnt_bodyid[j])).name for j in range(m.njnt) if m.jnt_type[j]==mujoco.mjtJoint.mjJNT_FREE]
    # Freeze articulated fixtures at the recorded pose; omit the dataset robot
    # so the viewer can add its own arm without baking a second robot into 3DGS.
    world=tree.find('worldbody');removed=[]
    def walk(parent):
        for body in list(parent.findall('body')):
            name=body.get('name','')
            if name.startswith(('robot','gripper')):
                parent.remove(body);removed.append(name);continue
            bid=m.body(name).id;pid=int(m.body_parentid[bid]);R=d.xmat[bid].reshape(3,3);Rp=d.xmat[pid].reshape(3,3)
            localR=Rp.T@R;localp=Rp.T@(d.xpos[bid]-d.xpos[pid]);q=Rotation.from_matrix(localR).as_quat()[[3,0,1,2]]
            body.set('pos',' '.join(map(str,localp)));body.set('quat',' '.join(map(str,q)))
            for key in ('euler','axisangle','xyaxes','zaxis'):body.attrib.pop(key,None)
            for joint in list(body.findall('joint')):
                if joint.get('type','hinge')!='free':body.remove(joint)
            walk(body)
    walk(world)
    for key in ('actuator','sensor','equality','contact','keyframe','tendon'):
        element=tree.find(key)
        if element is not None:tree.getroot().remove(element)
    compiled=mujoco.MjModel.from_xml_string(ET.tostring(tree.getroot()).decode());data=mujoco.MjData(compiled);mujoco.mj_forward(compiled,data)
    maxerr=0.
    for g in range(compiled.ngeom):
        name=compiled.geom(g).name
        if not name:continue
        original=m.geom(name).id
        maxerr=max(maxerr,float(np.linalg.norm(data.geom_xpos[g]-d.geom_xpos[original])))
    if maxerr>1e-5:raise ValueError(f'Native geometry placement changed by {maxerr} m')
    return tree,compiled,data,names,{'removed_robot_bodies':removed,'fixed_articulated_fixtures':True,'maximum_geom_position_error_m':maxerr}


def mesh_contract(model,data,names,scene):
    import mujoco,trimesh
    meshes=[];segments=[];groups=[];offset=0
    body_roots={n:model.body(n).id for n in names}
    def root_object(bid):
        while bid:
            for i,n in enumerate(names):
                if bid==body_roots[n]:return i+1
            bid=int(model.body_parentid[bid])
        return 0
    for g in range(model.ngeom):
        if model.geom_rgba[g,3]<.01:continue
        bid=int(model.geom_bodyid[g]);siblings=np.where(model.geom_bodyid==bid)[0]
        # robosuite's visual geoms are group 1; omit duplicate collision surfaces.
        if model.geom_group[g]==0 and np.any(model.geom_group[siblings]==1):continue
        typ=model.geom_type[g];size=model.geom_size[g]
        if typ==mujoco.mjtGeom.mjGEOM_MESH:
            idx=int(model.geom_dataid[g]);va=int(model.mesh_vertadr[idx]);vn=int(model.mesh_vertnum[idx]);fa=int(model.mesh_faceadr[idx]);fn=int(model.mesh_facenum[idx])
            mesh=trimesh.Trimesh(model.mesh_vert[va:va+vn].copy(),model.mesh_face[fa:fa+fn].copy(),process=False)
        elif typ==mujoco.mjtGeom.mjGEOM_BOX:mesh=trimesh.creation.box(extents=size*2)
        elif typ==mujoco.mjtGeom.mjGEOM_PLANE:mesh=trimesh.creation.box(extents=[8,8,.01]);mesh.apply_translation([0,0,-.005])
        elif typ==mujoco.mjtGeom.mjGEOM_SPHERE:mesh=trimesh.creation.icosphere(subdivisions=2,radius=size[0])
        elif typ==mujoco.mjtGeom.mjGEOM_CYLINDER:mesh=trimesh.creation.cylinder(radius=size[0],height=size[1]*2,sections=32)
        elif typ==mujoco.mjtGeom.mjGEOM_CAPSULE:mesh=trimesh.creation.capsule(radius=size[0],height=size[1]*2,count=[16,16])
        else:continue
        T=np.eye(4);T[:3,:3]=data.geom_xmat[g].reshape(3,3);T[:3,3]=data.geom_xpos[g];mesh.apply_transform(T)
        sid=root_object(bid);segments.extend([sid]*len(mesh.vertices));meshes.append(mesh)
    combined=trimesh.util.concatenate(meshes);scan=scene/'scans';scan.mkdir(exist_ok=True)
    combined.export(scan/'mesh_aligned_0.05.ply')
    save_json(scan/'segments.json',{'segIndices':segments})
    for i,name in enumerate(names):groups.append({'objectId':i+1,'label':object_label(name),'segments':[i+1],'native_body':name})
    save_json(scan/'segments_anno.json',{'segGroups':groups,'provenance':'native simulator instance geometry, GT-assisted'})
    return groups


def render_contract(tree,model,data,names,scene,views=80):
    import mujoco
    from scipy.spatial.transform import Rotation
    from PIL import Image
    from physicalview.render import look_at_w2c
    from agents.recon.behavior_extract import write_ply_xyzrgb
    width,height=1536,1024;fov=55.;f=height/(2*np.tan(np.deg2rad(fov)/2))
    K=np.array([[f,0,width/2],[0,f,height/2],[0,0,1.]])
    center=np.mean([data.xpos[model.body(n).id] for n in names],axis=0)
    # Native observation cameras cover the task side of the table. Sweep near
    # that side to avoid rendering through walls in these bounded simulator rooms.
    cid=model.camera('agentview').id;base=data.cam_xpos[cid].copy();az=np.arctan2(base[1]-center[1],base[0]-center[0])
    world=tree.find('worldbody');ET.SubElement(world,'camera',name='paper_camera',fovy=str(fov))
    model=mujoco.MjModel.from_xml_string(ET.tostring(tree.getroot()).decode());data=mujoco.MjData(model);mujoco.mj_forward(model,data)
    model.vis.global_.offwidth=width;model.vis.global_.offheight=height;renderer=mujoco.Renderer(model,height=height,width=width)
    camid=model.camera('paper_camera').id;poses=[];points=[];colors=[]
    imgdir=scene/'dslr/resized_undistorted_images';imgdir.mkdir(parents=True,exist_ok=True)
    depthdir=scene/'gt/depth';depthdir.mkdir(parents=True,exist_ok=True)
    try:
        for i in range(views):
            t=i/(views-1);yaw=az+(t-.5)*np.deg2rad(145);elev=np.deg2rad(25+20*((i%5)/4));radius=1.45
            position=center+radius*np.array([np.cos(elev)*np.cos(yaw),np.cos(elev)*np.sin(yaw),np.sin(elev)])
            w2c=look_at_w2c(position,center);c2w=np.linalg.inv(w2c);R=c2w[:3,:3]@np.diag([1,-1,-1]);q=Rotation.from_matrix(R).as_quat()[[3,0,1,2]]
            model.cam_pos[camid]=position;model.cam_quat[camid]=q;mujoco.mj_forward(model,data);renderer.update_scene(data,camera='paper_camera')
            rgb=renderer.render().copy();renderer.enable_depth_rendering();depth=renderer.render().copy();renderer.disable_depth_rendering()
            name=f'native_{i:04d}.png';Image.fromarray(rgb).save(imgdir/name);Image.fromarray(np.clip(depth*1000,0,65535).astype(np.uint16)).save(depthdir/name)
            ys,xs=np.mgrid[0:height:6,0:width:6];z=depth[ys,xs];valid=(z>.05)&(z<5)
            rays=np.stack([(xs-width/2)/f,(ys-height/2)/f,np.ones_like(xs)],-1)*z[...,None]
            xyz=rays[valid]@c2w[:3,:3].T+c2w[:3,3];points.append(xyz);colors.append(rgb[ys,xs][valid])
            quat=Rotation.from_matrix(w2c[:3,:3]).as_quat()[[3,0,1,2]];poses.append((name,w2c,quat))
    finally:renderer.close()
    xyz=np.concatenate(points);rgb=np.concatenate(colors);_,keep=np.unique(np.floor(xyz/.004).astype(np.int64),axis=0,return_index=True)
    write_ply_xyzrgb(scene/'init_points.ply',xyz[keep],rgb[keep])
    colmap=scene/'dslr/colmap';colmap.mkdir(exist_ok=True);lines=[]
    for i,(name,T,q) in enumerate(poses):
        lines.extend([f'{i+1} '+' '.join(map(str,[*q,*T[:3,3]]))+f' 1 {name}','0 0 -1'])
    (colmap/'images.txt').write_text('\n'.join(lines)+'\n')
    nerf=scene/'dslr/nerfstudio';nerf.mkdir(exist_ok=True);save_json(nerf/'transforms_undistorted.json',{'fl_x':f,'fl_y':f,'cx':width/2,'cy':height/2,'w':width,'h':height,'camera_model':'PINHOLE','k1':0,'k2':0,'p1':0,'p2':0,'frames':[{'file_path':name,'transform_matrix':np.linalg.inv(T)@np.diag([1,-1,-1,1])} for name,T,q in poses]})
    save_json(scene/'native-capture.json',{'views':views,'width':width,'height':height,'point_count':len(keep),'source':'native LIBERO MuJoCo scene and recorded initial state','native_robot_omitted':True,'articulated_fixtures_frozen':True,'upscaled':False,'publication_review':'pending'})


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--roster',required=True);ap.add_argument('--index',type=int,required=True);ap.add_argument('--root',required=True);ap.add_argument('--prepare-only',action='store_true');a=ap.parse_args()
    row=json.loads(Path(a.roster).read_text())[a.index];scene=Path(a.root)/'data'/row['scene'];scene.mkdir(parents=True,exist_ok=True)
    tree,m,d,names,receipt=source_model(row);tree.write(scene/'native-scene.xml');groups=mesh_contract(m,d,names,scene)
    save_json(scene/'source-receipt.json',{'source':row,'adaptation':receipt,'objects':groups,'capture_complete':False})
    if not a.prepare_only:
        render_contract(tree,m,d,names,scene)
        save_json(scene/'source-receipt.json',{'source':row,'adaptation':receipt,'objects':groups,'capture_complete':True})



def export_native_physics(scene, asset, objects, accepted_names):
    """Preserve native contact geometry/materials instead of re-convexifying a room.

    This is explicitly GT-assisted simulator evidence. Rejected generated objects
    remain static native fixtures, so clean-all and active-body sets agree.
    """
    import mujoco
    scene=Path(scene);asset=Path(asset)
    tree=ET.parse(scene/'native-scene.xml')
    source=mujoco.MjModel.from_xml_string(ET.tostring(tree.getroot()).decode())
    source_data=mujoco.MjData(source);mujoco.mj_forward(source,source_data)
    groups={g['objectId']:g for g in json.loads((scene/'scans/segments_anno.json').read_text())['segGroups']}
    renamed={};active=[];frozen=[]
    for obj in objects:
        name=f"obj_{obj['index']:02d}";native=groups[obj['gt_object_id']]['native_body']
        body=tree.find(f".//body[@name='{native}']")
        if body is None:raise ValueError(f'Native body missing: {native}')
        body.set('name',name);renamed[native]=name
        if name not in accepted_names:
            for joint in list(body.findall('joint'))+list(body.findall('freejoint')):
                body.remove(joint)
            frozen.append(name)
        else:active.append(name)
    # Discovery can omit a small or occluded native object entirely. Its splats
    # remain in the static background, so its native free joint must also be
    # frozen instead of moving an untracked collision body during simulation.
    for body in tree.findall('.//body'):
        name=body.get('name','')
        if name in active:continue
        joints=[j for j in body.findall('joint') if j.get('type')=='free']+body.findall('freejoint')
        for joint in joints:body.remove(joint)
        if joints and name not in frozen:frozen.append(name)
    if not active:raise ValueError('No accepted native bodies to simulate')
    model=mujoco.MjModel.from_xml_string(ET.tostring(tree.getroot()).decode())
    data=mujoco.MjData(model);mujoco.mj_forward(model,data)
    errors=[]
    for i in range(model.ngeom):
        name=model.geom(i).name
        if name:
            j=source.geom(name).id
            errors.append(float(np.linalg.norm(data.geom_xpos[i]-source_data.geom_xpos[j])))
    if max(errors,default=0)>1e-5:raise ValueError('Native collision geometry moved while naming objects')
    out=asset/'sim_export';out.mkdir(parents=True,exist_ok=True);tree.write(out/'scene.xml')
    record={'source':'native LIBERO MuJoCo contact model at recorded initial state',
        'source_xml':str(scene/'native-scene.xml'),'gt_assisted':True,'active':active,'frozen':frozen,
        'renamed_bodies':renamed,'maximum_geom_position_error_m':max(errors,default=0),
        'physical_parameters':'native masses, inertias, contact coefficients and fixture geometry retained',
        'native_robot_omitted':True,'generated_variants':'registered alternatives replace native selected-body collision only when chosen'}
    save_json(out/'native-physics-receipt.json',record)
    return record


if __name__=='__main__':main()
